<?php
/**
 * Shared curriculum lab data: used by curriculum.php and topics.php
 */
$curriculumData = [
    'mysql' => [
        'name'  => 'MySQL',
        'ver'   => '8.0+',
        'color' => 'mysql',
        'icon'  => 'MY',
        'labs'  => [
            ['num' => 1,  'title' => 'UNION: String (Single Quote)',       'category' => 'UNION-Based',       'difficulty' => 'easy',   'technique' => "Input wrapped in single quotes. Classic ' OR 1=1 and UNION SELECT to extract data from same/other tables.", 'status' => 'live'],
            ['num' => 2,  'title' => 'UNION: Integer (No Quotes)',         'category' => 'UNION-Based',       'difficulty' => 'easy',   'technique' => 'Numeric parameter with no quote wrapping. Direct integer injection into WHERE clause.', 'status' => 'live'],
            ['num' => 3,  'title' => 'UNION: String with Parentheses',    'category' => 'UNION-Based',       'difficulty' => 'easy',   'technique' => "Input wrapped in ('id'). Must close parenthesis before injecting UNION.", 'status' => 'live'],
            ['num' => 4,  'title' => 'UNION: Double Quotes',              'category' => 'UNION-Based',       'difficulty' => 'medium', 'technique' => 'Input wrapped in double quotes. Adapt injection to break out of " context.', 'status' => 'live'],
            ['num' => 5,  'title' => 'Error: ExtractValue / UpdateXML',   'category' => 'Error-Based',       'difficulty' => 'medium', 'technique' => 'XPath error functions: EXTRACTVALUE(1, CONCAT(0x7e, (SELECT ...))) and UPDATEXML leaking data in error messages.', 'status' => 'live'],
            ['num' => 6,  'title' => 'Error: Floor + GROUP BY',           'category' => 'Error-Based',       'difficulty' => 'medium', 'technique' => 'Classic double-query: SELECT COUNT(*), FLOOR(RAND(0)*2) x FROM ... GROUP BY x triggers duplicate key error containing data.', 'status' => 'live'],
            ['num' => 7,  'title' => 'Error: EXP / BIGINT Overflow',      'category' => 'Error-Based',       'difficulty' => 'hard',   'technique' => 'EXP(~(SELECT ...)) causes BIGINT overflow. Data leaks in arithmetic error message.', 'status' => 'live'],
            ['num' => 8,  'title' => 'Error: GTID_SUBSET / JSON_KEYS',    'category' => 'Error-Based',       'difficulty' => 'hard',   'technique' => 'Modern MySQL 5.7+ error vectors: GTID_SUBSET, JSON_KEYS, UUID_TO_BIN.', 'status' => 'live'],
            ['num' => 9,  'title' => 'Blind Boolean: SUBSTRING + IF',     'category' => 'Blind Injection',   'difficulty' => 'medium', 'technique' => 'No output, no errors. Use IF(SUBSTRING()) to extract character by character.', 'status' => 'live'],
            ['num' => 10, 'title' => 'Blind Boolean: REGEXP / LIKE',      'category' => 'Blind Injection',   'difficulty' => 'medium', 'technique' => 'Use REGEXP and LIKE pattern matching as boolean oracle.', 'status' => 'live'],
            ['num' => 11, 'title' => 'Blind Time: SLEEP() + IF',          'category' => 'Blind Injection',   'difficulty' => 'hard',   'technique' => 'Use IF(condition, SLEEP(3), 0) and measure response time to infer data.', 'status' => 'live'],
            ['num' => 12, 'title' => 'Blind Time: Heavy Query',           'category' => 'Blind Injection',   'difficulty' => 'hard',   'technique' => 'SLEEP blocked. Generate delays via cartesian joins on information_schema.', 'status' => 'live'],
            ['num' => 13, 'title' => 'Stacked Queries',                    'category' => 'Advanced',          'difficulty' => 'hard',   'technique' => 'Multi-statement execution via mysqli_multi_query. INSERT/UPDATE/DROP.', 'status' => 'live'],
            ['num' => 14, 'title' => 'INSERT / UPDATE Injection',          'category' => 'Advanced',          'difficulty' => 'hard',   'technique' => 'Injection in INSERT VALUES or UPDATE SET. Extract via error or subquery.', 'status' => 'live'],
            ['num' => 15, 'title' => 'ORDER BY / GROUP BY Injection',      'category' => 'Advanced',          'difficulty' => 'medium', 'technique' => 'Cannot use UNION. Use IF/CASE or error-based extraction.', 'status' => 'live'],
            ['num' => 16, 'title' => 'Header Injection: User-Agent',      'category' => 'Injection Vectors', 'difficulty' => 'hard',   'technique' => 'Application logs User-Agent to DB. Inject via HTTP header.', 'status' => 'live'],
            ['num' => 17, 'title' => 'Header Injection: Cookie',          'category' => 'Injection Vectors', 'difficulty' => 'hard',   'technique' => 'Session cookie value injected into SQL query.', 'status' => 'live'],
            ['num' => 18, 'title' => 'Second-Order Injection',             'category' => 'Injection Vectors', 'difficulty' => 'insane', 'technique' => 'Payload stored via registration, triggered on admin page.', 'status' => 'live'],
            ['num' => 19, 'title' => 'WAF Bypass: Keyword Blacklist',     'category' => 'WAF Bypass',        'difficulty' => 'insane', 'technique' => 'Bypass via inline comments, case mixing, %00 null bytes, double-URL encoding.', 'status' => 'live'],
            ['num' => 20, 'title' => 'WAF Bypass: GBK Wide Byte',         'category' => 'WAF Bypass',        'difficulty' => 'insane', 'technique' => "addslashes + GBK charset. Inject 0xbf27 to leave ' unescaped.", 'status' => 'live'],
        ],
    ],
    'pgsql' => [
        'name' => 'PostgreSQL', 'ver' => '16+', 'color' => 'pgsql', 'icon' => 'PG',
        'labs' => [
            ['num' => 1,  'title' => 'UNION: Basic String Injection',     'category' => 'UNION-Based',       'difficulty' => 'easy',   'technique' => "PostgreSQL UNION with string concat (||).", 'status' => 'live'],
            ['num' => 2,  'title' => 'UNION: Dollar-Quoting Bypass',      'category' => 'UNION-Based',       'difficulty' => 'medium', 'technique' => 'Use $$string$$ dollar-quoting to bypass quote filters.', 'status' => 'live'],
            ['num' => 3,  'title' => 'Error: CAST Type Mismatch',         'category' => 'Error-Based',       'difficulty' => 'medium', 'technique' => "CAST((SELECT...) AS INT) triggers type error leaking data.", 'status' => 'live'],
            ['num' => 4,  'title' => 'Blind Boolean: CASE + SUBSTRING',   'category' => 'Blind Injection',   'difficulty' => 'medium', 'technique' => 'Conditional error as boolean oracle.', 'status' => 'live'],
            ['num' => 5,  'title' => 'Blind Time: pg_sleep()',            'category' => 'Blind Injection',   'difficulty' => 'hard',   'technique' => "CASE WHEN cond THEN pg_sleep(5) ELSE pg_sleep(0) END.", 'status' => 'live'],
            ['num' => 6,  'title' => 'Stacked Queries: Multi-Statement',  'category' => 'Advanced',          'difficulty' => 'medium', 'technique' => "Full stacked query support. CREATE, INSERT, UPDATE.", 'status' => 'live'],
            ['num' => 7,  'title' => 'File Read: pg_read_file / COPY',    'category' => 'File Operations',   'difficulty' => 'hard',   'technique' => "Read server files via pg_read_file() or COPY FROM.", 'status' => 'live'],
            ['num' => 8,  'title' => 'File Write: COPY TO / lo_export',   'category' => 'File Operations',   'difficulty' => 'hard',   'technique' => "Write webshells via COPY TO or lo_export().", 'status' => 'live'],
            ['num' => 9,  'title' => 'RCE: COPY TO PROGRAM',             'category' => 'Code Execution',    'difficulty' => 'insane', 'technique' => "COPY (SELECT '') TO PROGRAM 'cmd'. Full RCE.", 'status' => 'live'],
            ['num' => 10, 'title' => 'RCE: Custom C Function (UDF)',      'category' => 'Code Execution',    'difficulty' => 'insane', 'technique' => "Upload .so via lo_import, CREATE FUNCTION for RCE.", 'status' => 'live'],
            ['num' => 11, 'title' => 'OOB: dblink + DNS Exfiltration',    'category' => 'Out-of-Band',       'difficulty' => 'insane', 'technique' => "DNS exfiltration via dblink_connect.", 'status' => 'live'],
            ['num' => 12, 'title' => 'Large Objects Abuse',                'category' => 'Advanced',          'difficulty' => 'hard',   'technique' => "lo_import, lo_get, lo_export chain for file R/W.", 'status' => 'live'],
            ['num' => 13, 'title' => 'XML Injection: xmlparse / xpath',   'category' => 'Advanced',          'difficulty' => 'hard',   'technique' => "Abuse PostgreSQL XML functions for error-based extraction.", 'status' => 'live'],
            ['num' => 14, 'title' => 'Privilege Escalation: ALTER ROLE',  'category' => 'Privilege Escalation', 'difficulty' => 'insane', 'technique' => "ALTER ROLE current_user SUPERUSER via stacked queries.", 'status' => 'live'],
            ['num' => 15, 'title' => 'INSERT / UPDATE Injection',          'category' => 'Injection Vectors', 'difficulty' => 'medium', 'technique' => "Injection in RETURNING clause for data extraction.", 'status' => 'live'],
        ],
    ],
    'sqlite' => [
        'name' => 'SQLite', 'ver' => 'v3.x', 'color' => 'sqlite', 'icon' => 'SL',
        'labs' => [
            ['num' => 1,  'title' => 'UNION: sqlite_master Enumeration',  'category' => 'UNION-Based',       'difficulty' => 'easy',   'technique' => "Query sqlite_master for table names and schemas.", 'status' => 'live'],
            ['num' => 2,  'title' => 'UNION: pragma_table_info()',        'category' => 'UNION-Based',       'difficulty' => 'easy',   'technique' => "Use pragma_table_info() to enumerate columns.", 'status' => 'live'],
            ['num' => 3,  'title' => 'Error: load_extension() Trigger',   'category' => 'Error-Based',       'difficulty' => 'medium', 'technique' => "Conditional error oracle via load_extension().", 'status' => 'live'],
            ['num' => 4,  'title' => 'Blind Boolean: hex(substr())',      'category' => 'Blind Injection',   'difficulty' => 'medium', 'technique' => "Character extraction via hex(substr()) comparison.", 'status' => 'live'],
            ['num' => 5,  'title' => 'Blind Time: RANDOMBLOB Heavy Query', 'category' => 'Blind Injection',  'difficulty' => 'hard',   'technique' => "No SLEEP(). CPU-bound timing with RANDOMBLOB().", 'status' => 'live'],
            ['num' => 6,  'title' => 'typeof() / zeroblob() Tricks',      'category' => 'Advanced',          'difficulty' => 'medium', 'technique' => "SQLite-specific functions for data inference.", 'status' => 'live'],
            ['num' => 7,  'title' => 'ATTACH DATABASE: File Write',       'category' => 'File Operations',   'difficulty' => 'hard',   'technique' => "ATTACH DATABASE to write PHP webshell to disk.", 'status' => 'live'],
            ['num' => 8,  'title' => 'RCE: load_extension()',            'category' => 'Code Execution',    'difficulty' => 'insane', 'technique' => "Load malicious .so/.dll for code execution.", 'status' => 'live'],
            ['num' => 9,  'title' => 'JSON Functions Injection',           'category' => 'Advanced',          'difficulty' => 'medium', 'technique' => "json_extract(), json_each() for extraction.", 'status' => 'live'],
            ['num' => 10, 'title' => 'WAF Bypass: No Standard Functions', 'category' => 'WAF Bypass',        'difficulty' => 'insane', 'technique' => "Use replace(), instr(), unicode(), char().", 'status' => 'live'],
        ],
    ],
    'mssql' => [
        'name' => 'MS SQL Server', 'ver' => '2022', 'color' => 'mssql', 'icon' => 'MS',
        'labs' => [
            ['num' => 1,  'title' => 'UNION: Basic String Injection',     'category' => 'UNION-Based',       'difficulty' => 'easy',   'technique' => "MSSQL UNION with string concat (+).", 'status' => 'live'],
            ['num' => 2,  'title' => 'Error: CONVERT / CAST',            'category' => 'Error-Based',       'difficulty' => 'medium', 'technique' => "CONVERT(INT, (SELECT...)) leaks data in error.", 'status' => 'live'],
            ['num' => 3,  'title' => 'Error: IN Operator Subquery',       'category' => 'Error-Based',       'difficulty' => 'medium', 'technique' => "1 IN (SELECT...) triggers conversion error.", 'status' => 'live'],
            ['num' => 4,  'title' => 'Blind Boolean: SUBSTRING + ASCII',  'category' => 'Blind Injection',   'difficulty' => 'medium', 'technique' => "Binary search on ASCII values of characters.", 'status' => 'live'],
            ['num' => 5,  'title' => 'Blind Time: WAITFOR DELAY',        'category' => 'Blind Injection',   'difficulty' => 'hard',   'technique' => "IF condition WAITFOR DELAY '0:0:5'.", 'status' => 'live'],
            ['num' => 6,  'title' => 'Stacked Queries: Full Control',     'category' => 'Advanced',          'difficulty' => 'medium', 'technique' => "Execute any statement: CREATE, INSERT, EXEC.", 'status' => 'live'],
            ['num' => 7,  'title' => 'xp_cmdshell: OS Commands',          'category' => 'Code Execution',    'difficulty' => 'hard',   'technique' => "Enable xp_cmdshell, EXEC xp_cmdshell 'whoami'.", 'status' => 'live'],
            ['num' => 8,  'title' => 'sp_OACreate: COM Object RCE',      'category' => 'Code Execution',    'difficulty' => 'insane', 'technique' => "OLE Automation for cmd exec without xp_cmdshell.", 'status' => 'live'],
            ['num' => 9,  'title' => 'Python sp_execute_external_script',  'category' => 'Code Execution',    'difficulty' => 'insane', 'technique' => "Execute Python code inside MSSQL for RCE.", 'status' => 'live'],
            ['num' => 10, 'title' => 'File Read: OPENROWSET(BULK)',       'category' => 'File Operations',   'difficulty' => 'hard',   'technique' => "Read arbitrary files via OPENROWSET.", 'status' => 'live'],
            ['num' => 11, 'title' => 'OOB: xp_dirtree DNS Exfil',        'category' => 'Out-of-Band',       'difficulty' => 'hard',   'technique' => "xp_dirtree UNC triggers DNS/SMB for exfil.", 'status' => 'live'],
            ['num' => 12, 'title' => 'OOB: fn_xe_file + UNC Path',       'category' => 'Out-of-Band',       'difficulty' => 'insane', 'technique' => "Stealthy exfil via fn_xe_file UNC path.", 'status' => 'live'],
            ['num' => 13, 'title' => 'Linked Servers Pivoting',           'category' => 'Privilege Escalation', 'difficulty' => 'insane', 'technique' => "OPENQUERY to pivot to other SQL servers.", 'status' => 'live'],
            ['num' => 14, 'title' => 'Impersonation: EXECUTE AS',        'category' => 'Privilege Escalation', 'difficulty' => 'hard', 'technique' => "EXECUTE AS LOGIN = 'sa' for privilege escalation.", 'status' => 'live'],
            ['num' => 15, 'title' => 'Header Injection: Referer',        'category' => 'Injection Vectors', 'difficulty' => 'hard',   'technique' => "Inject via Referer header logged to DB.", 'status' => 'live'],
            ['num' => 16, 'title' => 'INSERT: OUTPUT Clause',            'category' => 'Injection Vectors', 'difficulty' => 'medium', 'technique' => "MSSQL OUTPUT clause leaks inserted rows.", 'status' => 'live'],
            ['num' => 17, 'title' => 'WAF Bypass: Unicode Normalization', 'category' => 'WAF Bypass',        'difficulty' => 'insane', 'technique' => "IIS Unicode normalization: %%u0053ELECT.", 'status' => 'live'],
            ['num' => 18, 'title' => 'NTLM Hash Capture via SMB',         'category' => 'Advanced',          'difficulty' => 'insane', 'technique' => "Force auth to attacker SMB, capture NTLMv2.", 'status' => 'live'],
        ],
    ],
    'oracle' => [
        'name' => 'Oracle DB', 'ver' => '21c+', 'color' => 'oracle', 'icon' => 'OR',
        'labs' => [
            ['num' => 1,  'title' => 'UNION: FROM DUAL Required',        'category' => 'UNION-Based',       'difficulty' => 'medium', 'technique' => "Oracle requires FROM dual on every SELECT.", 'status' => 'live'],
            ['num' => 2,  'title' => 'UNION: all_tables Enumeration',     'category' => 'UNION-Based',       'difficulty' => 'medium', 'technique' => "Enumerate via all_tables, all_tab_columns.", 'status' => 'live'],
            ['num' => 3,  'title' => 'Error: XMLType()',                  'category' => 'Error-Based',       'difficulty' => 'hard',   'technique' => "XML parse error leaks data in message.", 'status' => 'live'],
            ['num' => 4,  'title' => 'Error: UTL_INADDR',                'category' => 'Error-Based',       'difficulty' => 'hard',   'technique' => "DNS resolve error contains query result.", 'status' => 'live'],
            ['num' => 5,  'title' => 'Error: CTXSYS.DRITHSX.SN',         'category' => 'Error-Based',       'difficulty' => 'hard',   'technique' => "Oracle Text function throws error with value.", 'status' => 'live'],
            ['num' => 6,  'title' => 'Blind Boolean: CASE + 1/0',        'category' => 'Blind Injection',   'difficulty' => 'medium', 'technique' => "Division-by-zero as boolean oracle.", 'status' => 'live'],
            ['num' => 7,  'title' => 'Blind Time: DBMS_PIPE',            'category' => 'Blind Injection',   'difficulty' => 'hard',   'technique' => "DBMS_PIPE.RECEIVE_MESSAGE pipe-based delay.", 'status' => 'live'],
            ['num' => 8,  'title' => 'Blind Time: Heavy Query',          'category' => 'Blind Injection',   'difficulty' => 'hard',   'technique' => "Cartesian join or UTL_HTTP timeout delay.", 'status' => 'live'],
            ['num' => 9,  'title' => 'OOB: UTL_HTTP.REQUEST',            'category' => 'Out-of-Band',       'difficulty' => 'insane', 'technique' => "HTTP callback with extracted data.", 'status' => 'live'],
            ['num' => 10, 'title' => 'OOB: HTTPURITYPE / XXE',           'category' => 'Out-of-Band',       'difficulty' => 'insane', 'technique' => "HTTPURITYPE().getclob() for OOB exfil.", 'status' => 'live'],
            ['num' => 11, 'title' => 'OOB: DBMS_LDAP.INIT',             'category' => 'Out-of-Band',       'difficulty' => 'insane', 'technique' => "LDAP-based data exfiltration.", 'status' => 'live'],
            ['num' => 12, 'title' => 'RCE: Java Stored Procedure',       'category' => 'Code Execution',    'difficulty' => 'insane', 'technique' => "Java Runtime.exec() via stored procedure.", 'status' => 'live'],
            ['num' => 13, 'title' => 'RCE: DBMS_SCHEDULER Job',          'category' => 'Code Execution',    'difficulty' => 'insane', 'technique' => "DBMS_SCHEDULER runs OS commands as oracle.", 'status' => 'live'],
            ['num' => 14, 'title' => 'Privilege Escalation: DBA Grant',   'category' => 'Privilege Escalation', 'difficulty' => 'insane', 'technique' => "Exploit AUTHID DEFINER to GRANT DBA.", 'status' => 'live'],
        ],
    ],
    'mariadb' => [
        'name' => 'MariaDB', 'ver' => 'v11+', 'color' => 'mariadb', 'icon' => 'MA',
        'labs' => [
            ['num' => 1,  'title' => 'UNION: MySQL-Compatible Basics',    'category' => 'UNION-Based',       'difficulty' => 'easy',   'technique' => "Verify UNION works identically to MySQL.", 'status' => 'live'],
            ['num' => 2,  'title' => 'CONNECT Engine: Remote Tables',     'category' => 'Advanced',          'difficulty' => 'hard',   'technique' => "Inject to read remote data via CONNECT engine.", 'status' => 'live'],
            ['num' => 3,  'title' => 'Spider Engine: Federated Injection', 'category' => 'Advanced',         'difficulty' => 'insane', 'technique' => "Pivot to other instances via Spider engine.", 'status' => 'live'],
            ['num' => 4,  'title' => 'Oracle Mode: PL/SQL Syntax',        'category' => 'Advanced',          'difficulty' => 'hard',   'technique' => "Exploit Oracle-style constructs in MariaDB.", 'status' => 'live'],
            ['num' => 5,  'title' => 'Sequence Object Injection',          'category' => 'Advanced',          'difficulty' => 'medium', 'technique' => "Extract data via NEXT VALUE FOR sequence.", 'status' => 'live'],
            ['num' => 6,  'title' => 'sys_exec UDF: OS Commands',         'category' => 'Code Execution',    'difficulty' => 'insane', 'technique' => "Full RCE via lib_mysqludf_sys.", 'status' => 'live'],
            ['num' => 7,  'title' => 'Error: SIGNAL / GET DIAGNOSTICS',   'category' => 'Error-Based',       'difficulty' => 'hard',   'technique' => "Custom error messages for extraction.", 'status' => 'live'],
            ['num' => 8,  'title' => 'Window Functions for Extraction',    'category' => 'Advanced',          'difficulty' => 'medium', 'technique' => "ROW_NUMBER(), RANK() OVER() in subqueries.", 'status' => 'live'],
        ],
    ],
    'mongodb' => [
        'name' => 'MongoDB', 'ver' => 'v7+', 'color' => 'mongodb', 'icon' => 'MG',
        'labs' => [
            ['num' => 1,  'title' => 'Auth Bypass: $ne Operator',         'category' => 'NoSQL Injection',   'difficulty' => 'easy',   'technique' => "Always-true condition via \$ne operator.", 'status' => 'live'],
            ['num' => 2,  'title' => 'Auth Bypass: $gt Operator',         'category' => 'NoSQL Injection',   'difficulty' => 'easy',   'technique' => "Password \$gt:'' matches any non-empty string.", 'status' => 'live'],
            ['num' => 3,  'title' => 'Blind Extraction: $regex',          'category' => 'NoSQL Injection',   'difficulty' => 'medium', 'technique' => "Extract data character-by-character with regex.", 'status' => 'live'],
            ['num' => 4,  'title' => 'Server-Side JS: $where',            'category' => 'Code Execution',    'difficulty' => 'hard',   'technique' => "Inject JavaScript into \$where clause.", 'status' => 'live'],
            ['num' => 5,  'title' => 'Aggregation Pipeline Injection',     'category' => 'NoSQL Injection',   'difficulty' => 'hard',   'technique' => "Inject \$match, \$group, \$project stages.", 'status' => 'live'],
            ['num' => 6,  'title' => '$lookup: Cross-Collection Access',  'category' => 'NoSQL Injection',   'difficulty' => 'hard',   'technique' => "Join from unauthorized collections via \$lookup.", 'status' => 'live'],
            ['num' => 7,  'title' => 'JSON Parameter Pollution',           'category' => 'Injection Vectors', 'difficulty' => 'medium', 'technique' => "Duplicate keys / arrays to inject operators.", 'status' => 'live'],
            ['num' => 8,  'title' => 'BSON: $type / $exists',             'category' => 'NoSQL Injection',   'difficulty' => 'medium', 'technique' => "Enumerate field types and existence.", 'status' => 'live'],
        ],
    ],
    'redis' => [
        'name' => 'Redis', 'ver' => 'v7+', 'color' => 'redis', 'icon' => 'RD',
        'labs' => [
            ['num' => 1,  'title' => 'CRLF Protocol Injection',            'category' => 'Command Injection', 'difficulty' => 'medium', 'technique' => "Break out of SET value with \\r\\n.", 'status' => 'live'],
            ['num' => 2,  'title' => 'Lua EVAL Injection',                 'category' => 'Code Execution',    'difficulty' => 'hard',   'technique' => "Inject Lua code into EVAL command.", 'status' => 'live'],
            ['num' => 3,  'title' => 'CONFIG SET: File Write',            'category' => 'File Operations',   'difficulty' => 'hard',   'technique' => "Write webshell via CONFIG SET dir/dbfilename.", 'status' => 'live'],
            ['num' => 4,  'title' => 'SLAVEOF: Data Exfiltration',        'category' => 'Out-of-Band',       'difficulty' => 'insane', 'technique' => "Replicate to attacker-controlled instance.", 'status' => 'live'],
            ['num' => 5,  'title' => 'MODULE LOAD: RCE',                  'category' => 'Code Execution',    'difficulty' => 'insane', 'technique' => "Load malicious .so module for full RCE.", 'status' => 'live'],
        ],
    ],
    'hql' => [
        'name' => 'HQL (Hibernate)', 'ver' => 'v6+', 'color' => 'hql', 'icon' => 'HQ',
        'labs' => [
            ['num' => 1,  'title' => 'Entity Name Injection',              'category' => 'HQL Injection',     'difficulty' => 'medium', 'technique' => "Inject into FROM EntityName clause.", 'status' => 'live'],
            ['num' => 2,  'title' => '.class Metadata Access',             'category' => 'HQL Injection',     'difficulty' => 'medium', 'technique' => "Leak class names via dot notation.", 'status' => 'live'],
            ['num' => 3,  'title' => 'Native Query Escape',                'category' => 'HQL Injection',     'difficulty' => 'hard',   'technique' => "Break out of HQL into native SQL.", 'status' => 'live'],
            ['num' => 4,  'title' => 'Criteria API Bypass',                'category' => 'HQL Injection',     'difficulty' => 'hard',   'technique' => "Inject into dynamic Criteria queries.", 'status' => 'live'],
            ['num' => 5,  'title' => 'Cache Poisoning',                    'category' => 'Advanced',          'difficulty' => 'insane', 'technique' => "Poison Hibernate second-level cache.", 'status' => 'live'],
        ],
    ],
    'graphql' => [
        'name' => 'GraphQL', 'ver' => 'API', 'color' => 'graphql', 'icon' => 'GQ',
        'labs' => [
            ['num' => 1,  'title' => 'Introspection: Schema Discovery',   'category' => 'Enumeration',       'difficulty' => 'easy',   'technique' => "Dump entire API schema via __schema.", 'status' => 'live'],
            ['num' => 2,  'title' => 'Field Suggestion Exploitation',      'category' => 'Enumeration',       'difficulty' => 'easy',   'technique' => "Enumerate via error message suggestions.", 'status' => 'live'],
            ['num' => 3,  'title' => 'Alias-Based Auth Bypass',            'category' => 'Auth Bypass',       'difficulty' => 'medium', 'technique' => "Access unauthorized data via aliases.", 'status' => 'live'],
            ['num' => 4,  'title' => 'Batching Attack',                    'category' => 'Auth Bypass',       'difficulty' => 'medium', 'technique' => "Brute-force OTP via batched mutations.", 'status' => 'live'],
            ['num' => 5,  'title' => 'Nested Query DoS + Data Extraction', 'category' => 'Advanced',          'difficulty' => 'hard',   'technique' => "Exploit circular references in deep nesting.", 'status' => 'live'],
        ],
    ],
];
